# Generated by Django 2.2.16 on 2022-08-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст нового комментария', verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.IntegerField(choices=[(1, 'Пришлось соврать, что смотрю порно, когда мама вошла в комнату'), (2, 'Каждый в моей комнате стал тупее'), (3, 'Лучше б я этого не видел'), (4, '3,6 - не отлично, но и не ужасно.'), (5, 'Видали мы и по-лучше'), (6, 'Потенциал не раскрыт'), (7, 'Пересматривать бы не стал'), (8, 'Моё уважение'), (9, 'Я ничего не понял, но сделаю вид, что всё понял'), (10, 'Рыдала вся маршрутка')], verbose_name='Баллы')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-pub_date'],
            },
        ),
    ]
